CREATE TABLE user(
	firstName VARCHAR(64) NOT NULL,
	lastName VARCHAR(64) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(64) NOT NULL,
	phone VARCHAR(64),
	id INT NOT NULL AUTO_INCREMENT,
	access INT NOT NULL DEFAULT 1,
	PRIMARY KEY(id)
);

CREATE TABLE appointments(
	day DATE NOT NULL,
	customer INT NOT NULL,
	package VARCHAR(64) NOT NULL,
	id INT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (id),
	FOREIGN KEY (customer) REFERENCES user(id)
);

CREATE TABLE galleries(
	id INT NOT NULL AUTO_INCREMENT,
	path VARCHAR(255) NOT NULL,
	highlightOne VARCHAR(255) NOT NULL,
	highlightTwo VARCHAR(255) NOT NULL,
	highlightThree VARCHAR(255) NOT NULL,
	highlightFour VARCHAR(255) NOT NULL,
	PRIMARY KEY(id)
);
